# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('XMU', '厦门大学'), ('BNU', '北京师范大学'), ('BUAA', '北京航空航天大学'), ('SJTU', '上海交通大学'), ('RENMIN', '中国人民大学'), ('FUDAN', '复旦大学'), ('ZJU', '浙江大学'), ('TONGJI', '同济大学'), ('BIT', '北京理工大学'), ('PKU', '北京大学'), ('THU', '清华大学')], default=None, max_length=300)),
            ],
        ),
    ]
